import { Pattern, PatternEntry } from "@/types/registry";
import { createTranslate } from "../../countries/registry/pattern";
import { usStates as states } from "../paths/states";
import { mapColors } from "../../colors";

const size = { width: 250, height: 125 };
const t = createTranslate(size, { defaultWidthFraction: 2 });
const c = Array(5).fill(mapColors.blackWhite[0]);

const pathsForOffset = (x: number, y: number) => [
  {
    path: "",
    image: {
      sprite: "plates",
      source: [x * 500, y * 250, 500, 250],
      destination: [
        size.width * 0.05,
        size.height * 0.05,
        size.width * 0.9,
        size.height * 0.9,
      ],
    },
  } as Pattern["paths"][number],
];

const patterns: Record<string, Pattern> = {
  alabama: { background: c[0], paths: pathsForOffset(0, 0) },
  alabamaBlur: { background: c[0], paths: pathsForOffset(0, 1) },
  alaska: { background: c[1], paths: pathsForOffset(1, 0) },
  alaskaBlur: { background: c[1], paths: pathsForOffset(1, 1) },
  arizona: { background: c[2], paths: pathsForOffset(2, 0) },
  arizonaBlur: { background: c[2], paths: pathsForOffset(2, 1) },
  arkansas: { background: c[3], paths: pathsForOffset(3, 0) },
  arkansasBlur: { background: c[3], paths: pathsForOffset(3, 1) },
  california: { background: c[4], paths: pathsForOffset(4, 0) },
  californiaBlur: { background: c[4], paths: pathsForOffset(4, 1) },
  colorado: { background: c[0], paths: pathsForOffset(0, 2) },
  coloradoBlur: { background: c[0], paths: pathsForOffset(0, 3) },
  connecticut: { background: c[1], paths: pathsForOffset(1, 2) },
  connecticutBlur: { background: c[1], paths: pathsForOffset(1, 3) },
  delaware: { background: c[2], paths: pathsForOffset(2, 2) },
  delawareBlur: { background: c[2], paths: pathsForOffset(2, 3) },
  florida: { background: c[3], paths: pathsForOffset(3, 2) },
  floridaBlur: { background: c[3], paths: pathsForOffset(3, 3) },
  georgia: { background: c[4], paths: pathsForOffset(4, 2) },
  georgiaBlur: { background: c[4], paths: pathsForOffset(4, 3) },
  hawaii: { background: c[0], paths: pathsForOffset(0, 4) },
  hawaiiBlur: { background: c[0], paths: pathsForOffset(0, 5) },
  idaho: { background: c[1], paths: pathsForOffset(1, 4) },
  idahoBlur: { background: c[1], paths: pathsForOffset(1, 5) },
  illinois: { background: c[2], paths: pathsForOffset(2, 4) },
  illinoisBlur: { background: c[2], paths: pathsForOffset(2, 5) },
  indiana: { background: c[3], paths: pathsForOffset(3, 4) },
  indianaBlur: { background: c[3], paths: pathsForOffset(3, 5) },
  iowa: { background: c[4], paths: pathsForOffset(4, 4) },
  iowaBlur: { background: c[4], paths: pathsForOffset(4, 5) },
  kansas: { background: c[0], paths: pathsForOffset(0, 6) },
  kansasBlur: { background: c[0], paths: pathsForOffset(0, 7) },
  kentucky: { background: c[1], paths: pathsForOffset(1, 6) },
  kentuckyBlur: { background: c[1], paths: pathsForOffset(1, 7) },
  louisiana: { background: c[2], paths: pathsForOffset(2, 6) },
  louisianaBlur: { background: c[2], paths: pathsForOffset(2, 7) },
  maine: { background: c[3], paths: pathsForOffset(3, 6) },
  maineBlur: { background: c[3], paths: pathsForOffset(3, 7) },
  maryland: { background: c[4], paths: pathsForOffset(4, 6) },
  marylandBlur: { background: c[4], paths: pathsForOffset(4, 7) },
  massachusetts: { background: c[0], paths: pathsForOffset(0, 8) },
  massachusettsBlur: { background: c[0], paths: pathsForOffset(0, 9) },
  michigan: { background: c[1], paths: pathsForOffset(1, 8) },
  michiganBlur: { background: c[1], paths: pathsForOffset(1, 9) },
  minnesota: { background: c[2], paths: pathsForOffset(2, 8) },
  minnesotaBlur: { background: c[2], paths: pathsForOffset(2, 9) },
  mississippi: { background: c[3], paths: pathsForOffset(3, 8) },
  mississippiBlur: { background: c[3], paths: pathsForOffset(3, 9) },
  missouri: { background: c[4], paths: pathsForOffset(4, 8) },
  missouriBlur: { background: c[4], paths: pathsForOffset(4, 9) },
  montana: { background: c[0], paths: pathsForOffset(0, 10) },
  montanaBlur: { background: c[0], paths: pathsForOffset(0, 11) },
  nebraska: { background: c[1], paths: pathsForOffset(1, 10) },
  nebraskaBlur: { background: c[1], paths: pathsForOffset(1, 11) },
  nevada: { background: c[2], paths: pathsForOffset(2, 10) },
  nevadaBlur: { background: c[2], paths: pathsForOffset(2, 11) },
  newHampshire: { background: c[3], paths: pathsForOffset(3, 10) },
  newHampshireBlur: { background: c[3], paths: pathsForOffset(3, 11) },
  newJersey: { background: c[4], paths: pathsForOffset(4, 10) },
  newJerseyBlur: { background: c[4], paths: pathsForOffset(4, 11) },
  newMexico: { background: c[0], paths: pathsForOffset(0, 12) },
  newMexicoBlur: { background: c[0], paths: pathsForOffset(0, 13) },
  newYork: { background: c[1], paths: pathsForOffset(1, 12) },
  newYorkBlur: { background: c[1], paths: pathsForOffset(1, 13) },
  northCarolina: { background: c[2], paths: pathsForOffset(2, 12) },
  northCarolinaBlur: { background: c[2], paths: pathsForOffset(2, 13) },
  northDakota: { background: c[3], paths: pathsForOffset(3, 12) },
  northDakotaBlur: { background: c[3], paths: pathsForOffset(3, 13) },
  ohio: { background: c[4], paths: pathsForOffset(4, 12) },
  ohioBlur: { background: c[4], paths: pathsForOffset(4, 13) },
  oklahoma: { background: c[0], paths: pathsForOffset(0, 14) },
  oklahomaBlur: { background: c[0], paths: pathsForOffset(0, 15) },
  oregon: { background: c[1], paths: pathsForOffset(1, 14) },
  oregonBlur: { background: c[1], paths: pathsForOffset(1, 15) },
  pennsylvania: { background: c[2], paths: pathsForOffset(2, 14) },
  pennsylvaniaBlur: { background: c[2], paths: pathsForOffset(2, 15) },
  rhodeIsland: { background: c[3], paths: pathsForOffset(3, 14) },
  rhodeIslandBlur: { background: c[3], paths: pathsForOffset(3, 15) },
  southCarolina: { background: c[4], paths: pathsForOffset(4, 14) },
  southCarolinaBlur: { background: c[4], paths: pathsForOffset(4, 15) },
  southDakota: { background: c[0], paths: pathsForOffset(0, 16) },
  southDakotaBlur: { background: c[0], paths: pathsForOffset(0, 17) },
  tennessee: { background: c[1], paths: pathsForOffset(1, 16) },
  tennesseeBlur: { background: c[1], paths: pathsForOffset(1, 17) },
  texas: { background: c[2], paths: pathsForOffset(2, 16) },
  texasBlur: { background: c[2], paths: pathsForOffset(2, 17) },
  utah: { background: c[3], paths: pathsForOffset(3, 16) },
  utahBlur: { background: c[3], paths: pathsForOffset(3, 17) },
  vermont: { background: c[4], paths: pathsForOffset(4, 16) },
  vermontBlur: { background: c[4], paths: pathsForOffset(4, 17) },
  virginia: { background: c[0], paths: pathsForOffset(0, 18) },
  virginiaBlur: { background: c[0], paths: pathsForOffset(0, 19) },
  washington: { background: c[1], paths: pathsForOffset(1, 18) },
  washingtonBlur: { background: c[1], paths: pathsForOffset(1, 19) },
  westVirginia: { background: c[2], paths: pathsForOffset(2, 18) },
  westVirginiaBlur: { background: c[2], paths: pathsForOffset(2, 19) },
  wisconsin: { background: c[3], paths: pathsForOffset(3, 18) },
  wisconsinBlur: { background: c[3], paths: pathsForOffset(3, 19) },
  wyoming: { background: c[4], paths: pathsForOffset(4, 18) },
  wyomingBlur: { background: c[4], paths: pathsForOffset(4, 19) },
};

const entries: PatternEntry<typeof patterns>[] = [
  {
    name: "Alabama",
    ...states.alabama,
    subjects: ["alabama", "alabamaBlur"],
    transform: t(states.alabama.meta, { scale: 1.8 }),
  },
  {
    name: "Alaska",
    ...states.alaska,
    subjects: ["alaska", "alaskaBlur"],
    transform: t(states.alaska.meta, { scale: 0.1, oy: 0.9 }),
  },
  {
    name: "Arizona",
    ...states.arizona,
    subjects: ["arizona", "arizonaBlur"],
    transform: t(states.arizona.meta, { scale: 1.8, ox: 0.1 }),
  },
  {
    name: "Arkansas",
    ...states.arkansas,
    subjects: ["arkansas", "arkansasBlur"],
    transform: t(states.arkansas.meta, { scale: 1.8 }),
  },
  {
    name: "California",
    ...states.california,
    subjects: ["california", "californiaBlur"],
    transform: t(states.california.meta, { scale: 0.8, oy: 0.5 }),
  },
  {
    name: "Colorado",
    ...states.colorado,
    subjects: ["colorado", "coloradoBlur"],
    transform: t(states.colorado.meta, { scale: 1.4, ox: 0.25 }),
  },
  {
    name: "Connecticut",
    ...states.connecticut,
    subjects: ["connecticut", "connecticutBlur"],
    transform: t(states.connecticut.meta, { ox: 0.7, oy: 0.1 }),
  },
  {
    name: "Delaware",
    ...states.delaware,
    subjects: ["delaware", "delawareBlur"],
    transform: t(states.delaware.meta, { scale: 1.3, ox: 0.2, oy: 0.2 }),
  },
  {
    name: "Florida",
    ...states.florida,
    subjects: ["florida", "floridaBlur"],
    transform: t(states.florida.meta, { scale: 0.5, ox: 0.7 }),
  },
  {
    name: "Georgia",
    ...states.georgia,
    subjects: ["georgia", "georgiaBlur"],
    transform: t(states.georgia.meta, { scale: 1.2, ox: 0.2, oy: 0.5 }),
  },
  {
    name: "Hawaii",
    ...states.hawaii,
    subjects: ["hawaii", "hawaiiBlur"],
    transform: t(states.hawaii.meta, { scale: 0.06, ox: 0.9, oy: 0.15 }),
  },
  {
    name: "Idaho",
    ...states.idaho,
    subjects: ["idaho", "idahoBlur"],
    transform: t(states.idaho.meta, { scale: 1.1, ox: 0.4, oy: 0.8 }),
  },
  {
    name: "Illinois",
    ...states.illinois,
    subjects: ["illinois", "illinoisBlur"],
    transform: t(states.illinois.meta, { scale: 1.2, ox: 0.3 }),
  },
  {
    name: "Indiana",
    ...states.indiana,
    subjects: ["indiana", "indianaBlur"],
    transform: t(states.indiana.meta, { scale: 1.4, ox: 0.3, oy: 0.4 }),
  },
  {
    name: "Iowa",
    ...states.iowa,
    subjects: ["iowa", "iowaBlur"],
    transform: t(states.iowa.meta, { scale: 1.1, ox: 0.4, oy: 0.1 }),
  },
  {
    name: "Kansas",
    ...states.kansas,
    subjects: ["kansas", "kansasBlur"],
    transform: t(states.kansas.meta, { ox: 0.5 }),
  },
  {
    name: "Kentucky",
    ...states.kentucky,
    subjects: ["kentucky", "kentuckyBlur"],
    transform: t(states.kentucky.meta, { scale: 0.6, oy: 0.6 }),
  },
  {
    name: "Louisiana",
    ...states.louisiana,
    subjects: ["louisiana", "louisianaBlur"],
    transform: t(states.louisiana.meta, { scale: 0.8, ox: 0.2 }),
  },
  {
    name: "Maine",
    ...states.maine,
    subjects: ["maine", "maineBlur"],
    transform: t(states.maine.meta, { ox: 0.4 }),
  },
  {
    name: "Maryland",
    ...states.maryland,
    subjects: ["maryland", "marylandBlur"],
    transform: t(states.maryland.meta, { scale: 0.4, ox: 0.4 }),
  },
  {
    name: "Massachusetts",
    ...states.massachusetts,
    subjects: ["massachusetts", "massachusettsBlur"],
    transform: t(states.massachusetts.meta, { scale: 0.5, oy: 0.5 }),
  },
  {
    name: "Michigan",
    ...states.michigan,
    subjects: ["michigan", "michiganBlur"],
    transform: t(states.michigan.meta, { ox: 0.9 }),
  },
  {
    name: "Minnesota",
    ...states.minnesota,
    subjects: ["minnesota", "minnesotaBlur"],
    transform: t(states.minnesota.meta, { ox: 0.2 }),
  },
  {
    name: "Mississippi",
    ...states.mississippi,
    subjects: ["mississippi", "mississippiBlur"],
    transform: t(states.mississippi.meta, { scale: 1.2, ox: 0.3 }),
  },
  {
    name: "Missouri",
    ...states.missouri,
    subjects: ["missouri", "missouriBlur"],
    transform: t(states.missouri.meta, { ox: 0.4 }),
  },
  {
    name: "Montana",
    ...states.montana,
    subjects: ["montana", "montanaBlur"],
    transform: t(states.montana.meta),
  },
  {
    name: "Nebraska",
    ...states.nebraska,
    subjects: ["nebraska", "nebraskaBlur"],
    transform: t(states.nebraska.meta, { scale: 0.9, ox: 0.6 }),
  },
  {
    name: "Nevada",
    ...states.nevada,
    subjects: ["nevada", "nevadaBlur"],
    transform: t(states.nevada.meta, { scale: 1.8, ox: 0.1 }),
  },
  {
    name: "New Hampshire",
    ...states.newHampshire,
    subjects: ["newHampshire", "newHampshireBlur"],
    transform: t(states.newHampshire.meta, { ox: 0.5 }),
  },
  {
    name: "New Jersey",
    ...states.newJersey,
    subjects: ["newJersey", "newJerseyBlur"],
    transform: t(states.newJersey.meta, { ox: 0.5 }),
  },
  {
    name: "New Mexico",
    ...states.newMexico,
    subjects: ["newMexico", "newMexicoBlur"],
    transform: t(states.newMexico.meta, { scale: 2 }),
  },
  {
    name: "New York",
    ...states.newYork,
    subjects: ["newYork", "newYorkBlur"],
    transform: t(states.newYork.meta, { scale: 0.7, ox: 0.2 }),
  },
  {
    name: "North Carolina",
    ...states.northCarolina,
    subjects: ["northCarolina", "northCarolinaBlur"],
    transform: t(states.northCarolina.meta, { scale: 0.5, oy: 0.1 }),
  },
  {
    name: "North Dakota",
    ...states.northDakota,
    subjects: ["northDakota", "northDakotaBlur"],
    transform: t(states.northDakota.meta, { scale: 1.2, ox: 0.3 }),
  },
  {
    name: "Ohio",
    ...states.ohio,
    subjects: ["ohio", "ohioBlur"],
    transform: t(states.ohio.meta, { scale: 1.5, ox: 0.2, oy: 0.5 }),
  },
  {
    name: "Oklahoma",
    ...states.oklahoma,
    subjects: ["oklahoma", "oklahomaBlur"],
    transform: t(states.oklahoma.meta, { scale: 0.8, ox: 0.3 }),
  },
  {
    name: "Oregon",
    ...states.oregon,
    subjects: ["oregon", "oregonBlur"],
    transform: t(states.oregon.meta, { scale: 1.2, ox: 0.3, oy: 0.4 }),
  },
  {
    name: "Pennsylvania",
    ...states.pennsylvania,
    subjects: ["pennsylvania", "pennsylvaniaBlur"],
    transform: t(states.pennsylvania.meta, { ox: 0.3, oy: 0.4 }),
  },
  {
    name: "Rhode Island",
    ...states.rhodeIsland,
    subjects: ["rhodeIsland", "rhodeIslandBlur"],
    transform: t(states.rhodeIsland.meta, { ox: 0.3, oy: 0.1 }),
  },
  {
    name: "South Carolina",
    ...states.southCarolina,
    subjects: ["southCarolina", "southCarolinaBlur"],
    transform: t(states.southCarolina.meta, { scale: 0.9, ox: 0.7, oy: 0.5 }),
  },
  {
    name: "South Dakota",
    ...states.southDakota,
    subjects: ["southDakota", "southDakotaBlur"],
    transform: t(states.southDakota.meta, { scale: 1.1, ox: 0.4 }),
  },
  {
    name: "Tennessee",
    ...states.tennessee,
    subjects: ["tennessee", "tennesseeBlur"],
    transform: t(states.tennessee.meta, { scale: 0.4, ox: 0.4, oy: 0.1 }),
  },
  {
    name: "Texas",
    ...states.texas,
    subjects: ["texas", "texasBlur"],
    transform: t(states.texas.meta, { scale: 0.8, ox: 0, oy: 0.2 }),
  },
  {
    name: "Utah",
    ...states.utah,
    subjects: ["utah", "utahBlur"],
    transform: t(states.utah.meta, { scale: 2, oy: 0.7 }),
  },
  {
    name: "Vermont",
    ...states.vermont,
    subjects: ["vermont", "vermontBlur"],
    transform: t(states.vermont.meta, { scale: 1.2, ox: 0.2, oy: 0.1 }),
  },
  {
    name: "Virginia",
    ...states.virginia,
    subjects: ["virginia", "virginiaBlur"],
    transform: t(states.virginia.meta, { scale: 0.5, ox: 0.9, oy: 0.4 }),
  },
  {
    name: "Washington",
    ...states.washington,
    subjects: ["washington", "washingtonBlur"],
    transform: t(states.washington.meta, { ox: 0.8, oy: 0.1 }),
  },
  {
    name: "West Virginia",
    ...states.westVirginia,
    subjects: ["westVirginia", "westVirginiaBlur"],
    transform: t(states.westVirginia.meta, { scale: 0.7, ox: 0.5, oy: 0.1 }),
  },
  {
    name: "Wisconsin",
    ...states.wisconsin,
    subjects: ["wisconsin", "wisconsinBlur"],
    transform: t(states.wisconsin.meta, { ox: 0.6 }),
  },
  {
    name: "Wyoming",
    ...states.wyoming,
    subjects: ["wyoming", "wyomingBlur"],
    transform: t(states.wyoming.meta, { scale: 1.5, ox: 0.1, oy: 0.1 }),
  },
];
// ].sort((a, b) => (a.tiny === true ? 1 : b.tiny === true ? -1 : 0));

const subjects = Object.keys(patterns).map((name) => ({
  name,
  selectable: name.endsWith("Blur"),
})) as {
  name: keyof typeof patterns;
}[];

export const usLicensePlates = { patterns, entries, subjects, size };
